server:
  session-timeout: 259200
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80

#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true    
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
appId: wxdb0f1262fb8b2266
appsecret: 445d47907a6b61c93521efe8e9b5b19a
access_token: https://api.weixin.qq.com/cgi-bin/token
jsapi_ticket: https://api.weixin.qq.com/cgi-bin/ticket/getticket
